name: Run CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
#  static-analysis:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v4
#      - name: Linting / Black
#        uses: psf/black@stable
#        with:
#          options: "--check --diff"
#          src: "./src"
#          use_pyproject: true
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .[dev]
      - name: Unit tests
        run: pytest